-- +goose Up
-- +goose StatementBegin
CREATE TABLE ctps (
                      id SERIAL PRIMARY KEY,
                      ctp_id VARCHAR(255) UNIQUE,
                      address VARCHAR(255),
                      type VARCHAR(255),
                      placement_type VARCHAR(255),
                      source VARCHAR(255),
                      administrative VARCHAR(255),
                      municipal VARCHAR(255),
                      start_date VARCHAR(255),
                      balance_holder VARCHAR(255),
                      polygon DOUBLE PRECISION[][],
                      center DOUBLE PRECISION[]
);


CREATE TABLE buildings (
                           unom INTEGER PRIMARY KEY,
                           ctp VARCHAR(255),
                           external_system_address TEXT,
                           external_system_id FLOAT8,
                           bti_address TEXT,
                           district TEXT,
                           area TEXT,
                           project_series TEXT,
                           number_of_floors FLOAT8,
                           number_of_entrances FLOAT8,
                           number_of_apartments FLOAT8,
                           total_area FLOAT8,
                           total_residential_area FLOAT8,
                           total_non_residential_area TEXT,
                           wear_and_tear_bti TEXT,
                           wall_materials TEXT,
                           emergency_status FLOAT8,
                           number_of_passenger_elevators FLOAT8,
                           number_of_freight_elevators FLOAT8,
                           roof_cleaning_priority TEXT,
                           roof_materials TEXT,
                           housing_fund_types FLOAT8,
                           mkd_statuses FLOAT8,
                           consumers TEXT,
                           group_type TEXT,
                           central_heating TEXT,
                           meter_brand TEXT,
                           meter_serial_number TEXT,
                           id_uu FLOAT8,
                           full_address TEXT,
                           ods_number TEXT,
                           ods_address TEXT,
                           serial_number TEXT,
                           city TEXT,
                           administrative_district TEXT,
                           municipal_district TEXT,
                           locality TEXT,
                           street TEXT,
                           house_number_type TEXT,
                           house_number TEXT,
                           building_number TEXT,
                           structure_number_type TEXT,
                           structure_number TEXT,
                           unad FLOAT8,
                           material TEXT,
                           purpose TEXT,
                           class TEXT,
                           type TEXT,
                           sign TEXT,
                           global_id FLOAT8,
                           obj_type TEXT,
                           address_x TEXT,
                           municipal_district_1 TEXT,
                           planning_element_name TEXT,
                           house_ownership_number_type TEXT,
                           intra_city_area TEXT,
                           adm_area TEXT,
                           district_1 TEXT,
                           nreg TEXT,
                           dreg TEXT,
                           n_fias TEXT,
                           d_fias TEXT,
                           kad_n TEXT,
                           kad_zu TEXT,
                           kladr TEXT,
                           tdoc TEXT,
                           ndoc TEXT,
                           ddoc TEXT,
                           adr_type TEXT,
                           vid TEXT,
                           sostad TEXT,
                           status TEXT,
                           geo_data DOUBLE PRECISION[][][],
                           geo_data_center DOUBLE PRECISION[],
                           id_ods FLOAT8,
                           phone_number TEXT
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS ctps, buildings;
-- +goose StatementEnd
