definitions:
  models.GeoDataFilter:
    properties:
      consumer_type:
        type: integer
      date:
        type: string
      district:
        type: boolean
      heat_network:
        type: integer
      tec:
        type: boolean
    type: object
  models.HandledUnom:
    properties:
      hours_to_cool:
        type: integer
      priority_group:
        type: integer
      unom:
        type: integer
    type: object
  models.Incident:
    properties:
      coordinates:
        items:
          type: number
        type: array
      ctp_id:
        type: string
      handled_unoms:
        items:
          $ref: '#/definitions/models.HandledUnom'
        type: array
      id:
        type: integer
      payload: {}
    type: object
  models.IncidentCreate:
    properties:
      ctp_id:
        type: string
      payload: {}
      unom:
        type: integer
    type: object
  models.IncidentShowUp:
    properties:
      coordinates:
        items:
          type: number
        type: array
      id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /building:
    get:
      consumes:
      - application/json
      parameters:
      - description: unom
        in: query
        name: unom
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get building
      tags:
      - building
  /building/by_ctp:
    get:
      consumes:
      - application/json
      parameters:
      - description: ctp
        in: query
        name: ctp
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get buildings by ctp
      tags:
      - building
  /ctp:
    get:
      consumes:
      - application/json
      parameters:
      - description: ctp_id STRING
        in: query
        name: ctp_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get ctp
      tags:
      - ctp
  /geo:
    get:
      consumes:
      - application/json
      parameters:
      - description: How many geos to return. If 0 then returns all
        in: query
        name: count
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get geo datas
      tags:
      - geo
  /geo/by_filters:
    put:
      consumes:
      - application/json
      parameters:
      - description: Filters
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.GeoDataFilter'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get by filter
      tags:
      - geo
  /geo/unom:
    get:
      consumes:
      - application/json
      parameters:
      - description: UNOM
        in: query
        name: unom
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get geo data by UNOM
      tags:
      - geo
  /incident:
    get:
      consumes:
      - application/json
      parameters:
      - description: Incident create
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully
          schema:
            $ref: '#/definitions/models.Incident'
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get incident by ID
      tags:
      - incident
    post:
      consumes:
      - application/json
      parameters:
      - description: Incident create
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.IncidentCreate'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create incident
      tags:
      - incident
  /incident/all:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Successfully
          schema:
            items:
              $ref: '#/definitions/models.IncidentShowUp'
            type: array
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all incidents
      tags:
      - incident
  /ml_predict_write:
    post:
      consumes:
      - application/json
      parameters:
      - description: Incident create
        in: query
        name: start_date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Save predicts from two weeks before start date and two weeks after
      tags:
      - ml
swagger: "2.0"
