info:
  contact: {}
paths:
  /building:
    get:
      consumes:
      - application/json
      parameters:
      - description: unom
        in: query
        name: unom
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get building
      tags:
      - building
  /building/by_ctp:
    get:
      consumes:
      - application/json
      parameters:
      - description: ctp
        in: query
        name: ctp
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get buildings by ctp
      tags:
      - building
  /ctp:
    get:
      consumes:
      - application/json
      parameters:
      - description: ctp_id STRING
        in: query
        name: ctp_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get ctp
      tags:
      - ctp
  /geo:
    get:
      consumes:
      - application/json
      parameters:
      - description: How many geos to return. If 0 then returns all
        in: query
        name: count
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get geo datas
      tags:
      - geo
  /geo/unom:
    get:
      consumes:
      - application/json
      parameters:
      - description: UNOM
        in: query
        name: unom
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get geo data by UNOM
      tags:
      - geo
swagger: "2.0"
